# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sculd"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ippei94da"]
  s.date = "2012-11-19"
  s.description = "Schedule management system using 'howm' like format. Plans, i.e., schedule(@), reminder(-), deadline(!), and tood(+), make events and tasks. Command 'sculd' can output events on each date and tasks with high priority. "
  s.email = "ippei94da@gmail.com"
  s.executables = ["dates", "sculd"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "CHANGES",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/dates",
    "bin/sculd",
    "lib/sculd.rb",
    "lib/sculd/event.rb",
    "lib/sculd/manager.rb",
    "lib/sculd/plan.rb",
    "lib/sculd/plan/deadline.rb",
    "lib/sculd/plan/reminder.rb",
    "lib/sculd/plan/schedule.rb",
    "lib/sculd/plan/todo.rb",
    "lib/sculd/task.rb",
    "sculd.gemspec",
    "spec/command_spec.rb",
    "spec/deadline_spec.rb",
    "spec/event_spec.rb",
    "spec/job_spec.rb",
    "spec/manager_spec.rb",
    "spec/plan_spec.rb",
    "spec/reminder_spec.rb",
    "spec/schedule/empty.dat",
    "spec/schedule/error.dat",
    "spec/schedule/schedule.dat",
    "spec/schedule_spec.rb",
    "spec/sculd_spec.rb",
    "spec/spec_helper.rb",
    "spec/todo_spec.rb"
  ]
  s.homepage = "http://github.com/ippei94da/sculd"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.11"
  s.summary = "Sculd, SChedULe Dealer."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.12.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<highline>, [">= 1.6.15"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.12.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.2.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<highline>, [">= 1.6.15"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.12.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.2.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<highline>, [">= 1.6.15"])
  end
end

